export const actionTypes = {
    UPDATE_WORDS: 'UPDATE_WORDS',
    SORT_WORDS: 'SORT_WORDS',
    SET_SORTING: 'SET_SORTING',
    FETCH_DEFINITION_PENDING: 'FETCH_DEFINITION_PENDING',
    FETCH_DEFINITION_SUCCESS: 'FETCH_DEFINITION_SUCCESS',
    FETCH_DEFINITION_ERROR: 'FETCH_DEFINITION_ERROR'
}

export const sorting = {
    ALPHABETICAL: 'ALPHABETICAL',
    REVERSE_ALPHABETICAL: 'REVERSE_APLHABETICAL',
    INCREASING_OCCURRENCES: 'INCREASING_OCCURENCES',
    DESCREASING_OCCURENCES: 'DECREASING_OCCURENCES',
    NONE: 'NONE',
    TIME_ADDED: 'TIME_ADDED',
    REVERSE_TIME_ADDED: 'REVERSE_TIME_ADDED'
}

export const DEFINITION_ENDPOINT = '/definition/'